data_path: ./concept_library/visual/segments
model: swin_s
device: cuda
batch_size: 256
workers: 16
resume: ''
world_size: 1
dist_url: env://
interpolation: bicubic
val_resize_size: 246
val_crop_size: 224
weights: IMAGENET1K_V1
backend: pil
