data_path: ./concept_library/visual/segments
model: vit_l_16
device: cuda
batch_size: 32
workers: 16
resume: ''
world_size: 1
dist_url: env://
interpolation: bilinear
val_resize_size: 512
val_crop_size: 512
weights: IMAGENET1K_SWAG_E2E_V1
backend: pil
