data_path: ./concept_library/visual/segments
model: vit_b_16
device: cuda
batch_size: 128
workers: 16
resume: ''
world_size: 1
dist_url: env://
interpolation: bilinear
val_resize_size: 256
val_crop_size: 224
weights: IMAGENET1K_V1
backend: pil
